### PR TITLE
#265 ClickHouseResultSet.getTimestamp(col, calendar) implementation

### LINKED ISSUE #265: ClickHouseResultSet.getTimestamp(col, calendar) implementation proposal
### Environment

- OS version: Windows
- JDK version: 8
- ClickHouse Server version: 20.11.5.18
- ClickHouse Native JDBC version: 2.4.3
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Other descriptions
`ClickHouseResultSet.getTimestamp(name, calendar)` & `ClickHouseResultSet.getTimestamp(index, calendar)` are not implemented but the current implementation of `DataTypeDateTime` prevents us from doing it as the initial time zone (coming from the server or defined by the user in the connection properties) is unknown once in `ClickHouseResultSet.getTimestamp` (as we only manipulate `Timestamp` object) 

The only solution would be to modify `DataTypeDateTime` to return something different from `Timestamp` but something that includes the source timezone.

In:

- `ClickHouseResultSet.getTimestamp(name)` : No special processing has to be done
- `ClickHouseResultSet.getTimestamp(index)` : No special processing has to be done
- `ClickHouseResultSet.getTimestamp(name, calendar)` : Data tz is present and give the ability to change it per to user request
- `ClickHouseResultSet.getTimestamp(index, calendar)` : Data tz is present and give the ability to change it per to user request

Sound ok for you ?

### PR DESCRIPTION
**Pull request by sbouchex**
Closes #265

### CODE REVIEW

**Comment by sundy-li** [comment]
Happy new year! Thanks for the contribution, I'll look into it later.

**Comment by sbouchex** [comment]
@sundy-li Happy new year to you also. JUnit are failing, I will look at them next week.

**Comment by pan3793** [comment]
@sbouchex Thanks for working on this PR. 
I have one question, why should introduce `TimeZonedTimestamp`? `ZonedDateTime` contains enough information, both nano epoch and `ZoneId`. In my own view, I prefer keep `DataTime` and `DateTime64` serde type as `ZonedDateTime`, and convert them in JDBC interface.

**Comment by sbouchex** [comment]
@pan3793 I have decided to use my own TimeZonedTimestamp in order to have a compact type with just seconds, nanos and tz fields. Using ZonedDateTime may be possible but seconds, nanos are not directly accessible (and stored) and will requires changes & conversion which is error-prone.

**Comment by pan3793** [comment]
@sbouchex I highly recommend to use `ZonedDateTime` and put all conversion stuffs to `DateTimeUtil` instead of making your own wheels. **Time System** is a profound topic, even the JDK author make a mistake then millions of Javaer headache with legacy `Date` API.

**Comment by sbouchex** [comment]
@pan3793 ok, I'll change that

**Comment by pan3793** [comment]
move to #288

**Pull request closed without merging**
