### PR TITLE
Add ipv4 insert

### PR DESCRIPTION
**Pull request by ico01**
see #126

### CODE REVIEW

**Comment by sundy-li** [comment]
LGTM, could u create a test for this type ?

**Comment by ico01** [comment]
> LGTM, could u create a test for this type ?

ok , i'll create a test

**Comment by ico01** [comment]
@sundy-li  when query should i return string or long ?

**Comment by ico01** [comment]
the travis ci seems to be blocked. can you stop it and then run the test ?

**Pull request merged**
