### PR TITLE
Add decimal  support

### PR DESCRIPTION
**Pull request by kifile**
Add support for decimal data type.

Decimal128 is unsupported.

### CODE REVIEW

**Comment by sundy-li** [comment]
Hi, could u plz provide some tests?

**Comment by kifile** [comment]
@sundy-li Hi, I have complete the test case.

**Comment by sundy-li** [comment]
There are some build errors at:  https://travis-ci.org/housepower/ClickHouse-Native-JDBC/jobs/624623414

(I am handling the github traivs app, so we can't see the ci status on this page.)

**Comment by kifile** [comment]
@sundy-li hi sundy, i try to fix the exceptions, but found caused by connection.createStatement(), and i run the test case success in local. So plz check the connection to clickhouse is correct.

**Comment by sundy-li** [comment]
ok, I will check the tests. Thank you.

**Pull request merged**
