### PR TITLE
Fix #115 reset Block when clearBatch

### LINKED ISSUE #115: 2.0 stable raise BufferOverflowException
### JDBC version in pom.xml
2.0-stable

### ClickHouse version
any version

### Error  logs
 java.nio.BufferOverflowException

### Steps to reproduce
Using native-jdbc for batch insert, if execute the same statement more than once, the application will crash.

And it is caused by clearBatch() int the ClickHousePreparedInsertStatement didn't recycle the Block used in last execution.

### PR DESCRIPTION
**Pull request by kifile**

### CODE REVIEW

**Comment by kifile** [comment]
Still some problem, after clear Block ,it can do the batch Insert, but query is not work.

**Comment by sundy-li** [comment]
Thanks for the fix.

**Comment by sundy-li** [comment]
@kifile  I think we can force to call `initBlockIfPossible` when we clear the batch.

**Comment by kifile** [comment]
@sundy-li  Actually, we can't. 
If we re-init the block after the batch insert, the connection state will always be WAIT_FOR_INSERT except call close() explicitly.

Once user execute a batch insert following with a query operation, the query will be failed because of the unneccessary init operation.

**Comment by kifile** [comment]
And in `sendInsertRequest`,  you have sent a empty block to the clickhouse-server to mark the insert operation finished.

Before the next `sendInsertRequest` called,  `sendSampleBlock` should be called.

**Comment by sundy-li** [comment]
Got that,  so the `prepared-statment` will be reused for many times, previously only the construct function we call the `sendSampleBlock `.  Now with your code, we check-in this in `setObject`

**Comment by kifile** [comment]
That's right. There is a better way to resolve the problem.

Call `sendSampleBlock` in the constructor to get the information about the insert block, and close it immediately. 
Call `sendSampleBlock` before `sendInsertRequest` in `executeBatch` to ensure the connection state is corret.

**Comment by ssky1** [comment]
Hi sundy-li,

I just downloaded the clickhouse-native-jdbc-2.1-stable.jar (Last update 04. April 2020) and the clearBatch method is not implemented yet 

Can I have the .jar including the correction ?

thanks

**Comment by kifile** [comment]
@ssky1 2.1-stable is using a stupid way to resovle the reuse problem, but still work.

**Comment by sundy-li** [comment]
> @ssky1 2.1-stable is using a stupid way to resovle the reuse problem, but still work.

That's right.  v2.1 can work, but I am still thinking about how to handle it the better way.

1. Let the users/Datasources control the connection State, JDBC did not involve in.  

2. When PrepareStmt begins, we send an extra but empty block insert query to ClickHouse. After this, every execute query is atomic. #121  

The reason is that BatchInsert Query needs two-level requests(getSampleBlock, batch insert), during the requests, we can't do anything else. 

Currently, both way we can't use the connections on parallel, so the users must ensure that. Why not the users to ensure more? So I think the first way may be better. It's stupid, but it works...

**Pull request merged**
