### PR TITLE
feature:support map field

### PR DESCRIPTION
**Pull request by TheXs**
Hi, there.
Thanks for creating such a passionative tool, it really helped me out from the insert efficiency of the ck java-based client. Just noticed that map field hasn't been support by default so far and I think it would be a graceful to having it. Check it out and thanks for all your effort! Any question pls be free to approaching:)

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks for contribution, have a quick look on the PR, could you please also add unit test to verify the code works as expected, and we has some code style check and license rules, you can check the fail messages in CI log.

**Comment by TheXs** [comment]
> Thanks for contribution, have a quick look on the PR, could you please also add unit test to verify the code works as expected, and we has some code style check and license rules, you can check the fail messages in CI log.

Hi, there. 
This is my first PR and I am currently not quite sure about how to solve the  error PR comment error(you can check it in the CI log). Is it supposed relating to any mechanism on first PR? Best regards!

**Comment by pan3793** [comment]
Thanks for contributions. Just ignore the PR comment error, it's a known issue. I will take a look when have time.

**Comment by JasonBabylon** [comment]
Great Job ! 👍

**Pull request closed without merging**
